[package]
name = "stern"
version.workspace = true
edition.workspace = true

# Tests for SlintExecutor. i_slint_backend_testing requires to be ran on separate process
# since it uses static variable.

[[test]]
path = "tests/slint_executor/panics_with_tokio.rs"
name = "slint_executor_panics_with_tokio"

[[test]]
path = "tests/slint_executor/simple.rs"
name = "slint_executor_simple"

[[test]]
path = "tests/slint_executor/propagates_panic.rs"
name = "slint_executor_propagates_panic"

[dependencies]
stern-macros = { workspace = true }

slint = { workspace = true }

# utilities
thiserror = { workspace = true }
strum = { workspace = true, features = ["derive"] }
parking_lot = { workspace = true }
derive_more = { workspace = true, features = ["debug"] }

# async libraries
futures-util = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "macros"] }
tokio-util = { workspace = true }

# smol family
async-io = { workspace = true, features = ["tracing"] }
async-task = { workspace = true }
async-executor = { workspace = true }

[dev-dependencies]
tokio-stream = { workspace = true, features = ["sync"] }
i-slint-backend-testing = { workspace = true }
trybuild = { workspace = true }
tracing-subscriber = { workspace = true }
