[package]
name = "stern"
version.workspace = true
edition.workspace = true

[dependencies]
stern-macros = { workspace = true }

slint = { workspace = true }

thiserror = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "macros"] }
tokio-util = { workspace = true }
parking_lot = { workspace = true }
derive_more = { workspace = true, features = ["debug"] }
