//! Heavily Inspired by Jetpack Navigation 3 (see https://developer.android.com/guide/navigation).
//!
//! Key types of this module are:
//! - [`NavHost`]
//! - [`NavController`]
//! - [`NavDestination`]

use std::{
    cell::RefCell,
    collections::{HashMap, HashSet},
    fmt::Debug,
    hash::Hash,
    rc::Rc,
};
use strum::IntoEnumIterator;
use thiserror::Error;
use tracing::debug;

/// Watches [`NavController`] and prepares `ViewModel`s before navigating to the route.
///
/// Typically you would attach [`NavHost`] to [`NavController`] using [`NavHost::builder()`].
pub struct NavHost<R: RouteEnum> {
    destinations: HashMap<R::Kind, Box<dyn NavDestination<R>>>,
}

impl<R> NavHost<R>
where
    R: RouteEnum,
{
    fn on_navigate(&mut self, route: &R) {
        debug!(?route, "NavHost: searching registered destination");
        let kind: R::Kind = route.into();
        let dest = self.destinations.get(&kind).unwrap(); // checked in Builder
        dest.load(route);
    }

    pub fn builder(nav_controller: NavController<R>) -> NavHostBuilder<R> {
        NavHostBuilder::<R> {
            nav_controller,
            destinations: Vec::new(),
        }
    }
}

/// Enum to represent navigation routes.
///
/// [`Kind`] is typically generated by [`strum::EnumDiscriminants`].
///
/// Usually [`Kind`] and [`SlintKind`] have completely same variants,
/// but we can't derive [`Hash`] or [`strum::IntoEnumIterator`] from Slint's type for now.
///
/// [`Kind`]: Self::Kind
/// [`SlintKind`]: Self::SlintKind
pub trait RouteEnum: Debug + Sized + 'static {
    type Kind: Debug
        + Copy
        + Eq
        + Hash
        + IntoEnumIterator
        + for<'a> From<&'a Self>
        + From<Self>
        + Into<Self::SlintKind>
        + 'static;

    type SlintKind;
}

/// Builder for [`NavHost`]. You can cerate new builder from [`NavHost::builder()`].
///
/// Created [`NavHost`] will be moved to [`NavController`] by calling [`NavController::subscribe_on_navigate()`].
pub struct NavHostBuilder<R: RouteEnum> {
    nav_controller: NavController<R>,
    destinations: Vec<Box<dyn NavDestination<R>>>,
}

impl<R> NavHostBuilder<R>
where
    R: RouteEnum,
{
    /// Registers [`NavDestination`] to the host.
    ///
    /// Corresponds to `NavHost`'s block in Jetpack Navigation 3, for instance:
    /// ```kotlin
    /// NavHost(navController = navController, startDestination = Profile) {
    ///     composable<Profile> { ProfileScreen( /* ... */ ) }
    ///     composable<FriendsList> { FriendsListScreen( /* ... */ ) }
    /// }
    /// ```
    pub fn register(mut self, dest: impl NavDestination<R> + 'static) -> Self {
        self.destinations.push(Box::new(dest));
        self
    }

    pub fn finish(self) -> Result<(), NavHostBuilderError<R>> {
        // TODO: 重複とかの確認
        let mut map = HashMap::new();
        let mut duplicates = HashSet::new();
        for dest in self.destinations {
            if let Some(old) = map.insert(dest.route(), dest) {
                duplicates.insert(old.route());
            }
        }
        if !duplicates.is_empty() {
            return Err(NavHostBuilderError::DuplicatedRegisteration(duplicates));
        }

        let mut missings = HashSet::new();
        R::Kind::iter().for_each(|route| {
            if !map.contains_key(&route) {
                missings.insert(route);
            }
        });
        if !missings.is_empty() {
            return Err(NavHostBuilderError::NotAllRoutesRegistered(missings));
        }

        let mut host = NavHost { destinations: map };
        self.nav_controller.subscribe_on_navigate(move |route| {
            host.on_navigate(route);
        });
        Ok(())
    }
}

/// Error returned from [`NavHostBuilder::finish()`].
#[derive(Debug, Error)]
pub enum NavHostBuilderError<R: RouteEnum> {
    #[error("destinations for some routes are not registered: {0:?}")]
    NotAllRoutesRegistered(HashSet<R::Kind>),
    #[error("destination for {0:?} are registered multiple times")]
    DuplicatedRegisteration(HashSet<R::Kind>),
}

pub trait NavDestination<R: RouteEnum> {
    /// Load viewmodel's state with given arguments by `route`.
    ///
    /// Invariant: given `route`'s variant is the variant which returned `true` in [NavDestination::matches()].
    fn load(&self, route: &R);

    fn route(&self) -> R::Kind;
}

/// Clonable handle for navigating routes.
#[derive(Debug)]
pub struct NavController<R: RouteEnum>(Rc<RefCell<NavControllerInner<R>>>);

impl<R> NavController<R>
where
    R: RouteEnum,
{
    pub fn new<F>(default_route: R, route_property_setter: F) -> Self
    where
        F: Fn(R::SlintKind) + 'static,
    {
        Self(Rc::new(RefCell::new(NavControllerInner::new(
            default_route,
            route_property_setter,
        ))))
    }

    /// Navigates to the specified route. The function needs to be called from the thread running slint event loop, if `route_property_setter`
    /// passed in [`NavController::new()`] calls any slint function.
    pub fn navigate(&self, route: R) {
        self.0.borrow_mut().navigate(route);
    }

    fn subscribe_on_navigate<F>(&self, f: F)
    where
        F: FnMut(&R) + 'static,
    {
        self.0.borrow_mut().subscribe_on_navigate(f);
    }
}

impl<R> Clone for NavController<R>
where
    R: RouteEnum,
{
    /// Cheap clone (same as [`Rc::clone()`][std::rc::Rc])
    fn clone(&self) -> Self {
        Self(Rc::clone(&self.0))
    }
}

struct NavControllerInner<R: RouteEnum> {
    route_property_setter: Box<dyn Fn(R::SlintKind)>,
    on_navigate: Option<Box<dyn FnMut(&R)>>,
}

impl<R> Debug for NavControllerInner<R>
where
    R: RouteEnum,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NavControllerInner")
            .field(
                "on_navigate",
                &if self.on_navigate.is_some() {
                    "Some( .. )"
                } else {
                    "None"
                },
            )
            .finish()
    }
}

impl<R> NavControllerInner<R>
where
    R: RouteEnum,
{
    fn new<F>(default_route: R, route_property_setter: F) -> Self
    where
        F: Fn(R::SlintKind) + 'static,
    {
        // FIXME: このタイミングでは`NavHost.on_navigate()`が呼ばれない
        let kind: R::Kind = default_route.into();
        route_property_setter(kind.into().into());
        Self {
            on_navigate: None,
            route_property_setter: Box::new(route_property_setter),
        }
    }

    fn navigate(&mut self, route: R) {
        debug!(?route, "navigating");
        if let Some(on_navigate) = &mut self.on_navigate {
            (on_navigate.as_mut())(&route);
        }

        let kind: R::Kind = route.into();
        let ui_route: R::SlintKind = kind.into();
        (self.route_property_setter)(ui_route);
    }

    fn subscribe_on_navigate<F>(&mut self, f: F)
    where
        F: FnMut(&R) + 'static,
    {
        self.on_navigate = Some(Box::new(f))
    }
}

#[cfg(test)]
mod tests {
    //use crate::presentation::start::StartScreenDestination;

    // use super::*;

    #[test]
    fn navhost_builder_returns_err_when_not_all_routes_registered() {
        todo!()
        /*let nav_controller = NavController::new(ui::NavRoute::Start, |route| {
            println!("dummy");
        });
        let application =
        NavHost::builder(nav_controller).register(StartScreenDestination::new(application));*/
    }

    #[test]
    fn navhost_builder_returns_err_when_registerations_are_duplicated() {
        todo!()
    }
}
