use crate::{
    generate::adopter_inner,
    mapper::parse::DefineMapperInput,
    parse::{InnerGlobalComponent, PropertyField, RouteMacroAttr},
};
use heck::{ToSnakeCase, ToUpperCamelCase};
use quote::{IdentFragment, format_ident, quote};
use syn::{Ident, ItemEnum, ext::IdentExt, parse_macro_input};

#[macro_use]
#[cfg(test)]
mod test_helper_macros {
    /// Utility macro to return the name of the current function.
    ///
    /// Copy & Pasted from <https://github.com/mitsuhiko/insta/blob/master/insta/src/macros.rs>.
    #[doc(hidden)]
    macro_rules! function_name {
        () => {{
            fn f() {}
            let mut name = ::core::any::type_name_of_val(&f)
                .strip_suffix("::f")
                .unwrap_or("");
            while let Some(rest) = name.strip_suffix("::{{closure}}") {
                name = rest;
            }
            name
        }};
    }

    /// Creates new [`tempfile::NamedTempFile`] prefixed with function name.
    macro_rules! new_trybuild_file {
        () => {
            ::tempfile::Builder::new()
                .prefix(format!("{}.", function_name!()).as_str())
                .suffix(".rs")
                .tempfile()
                .unwrap()
        };
    }
}

mod generate;
mod mapper;
mod parse;

/// Attribute used on `NavRoute` enum.
///
/// This macro generates:
/// - Sub-enum which implements [`Route::Kind`][stern::Route::Kind]
/// - `Into<ui::NavRoute>` implementation for `NavRoute`
/// - Re-exports for types generated by [`adopter`] attribute, based on its name
/// - `ViewModelOwner` which owns all viewmodels
///
/// Since the macro re-exports types from `slint_generated<YourWindow>` module, it
/// must be used in the same module as which you call [`slint::include_modules!`].
///
/// If your adopter's name is `XxxAdopter`, the variant should be `Xxx`.
///
/// ## Options
/// - slint_type: Route enum type in your slint file. default value: `UiNavRoute`
#[proc_macro_attribute]
pub fn route(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let item: ItemEnum = parse_macro_input!(item);
    let attr: RouteMacroAttr = parse_macro_input!(attr);
    let item_name = &item.ident;
    let slint_typ_name = attr.slint_type_name;

    let kind_enum_name = format_ident!("{}Kind", item_name);

    let re_exports = {
        let typs = item.variants.iter().map(|v| {
            let vm_trait_name = viewmodel_trait_ident(&v.ident);
            let states_struct_name = state_struct_ident(&v.ident);
            let mapper_trait_name = mapper_trait_ident(&v.ident);
            quote! {
                #vm_trait_name, #states_struct_name, #mapper_trait_name,
            }
        });
        quote! {
            pub use self::slint_generatedAppWindow::{
                #(#typs)*
            };
        }
    };
    let item_with_attr = quote! {
        #[derive(stern::re_exports::EnumDiscriminants)]
        #[strum_discriminants(name(#kind_enum_name), derive(stern::re_exports::EnumIter, Hash))]
        #item
    };
    let into_impl = {
        let match_arms = item.variants.iter().map(|v| {
            let ident = &v.ident;
            quote! {
                Self::#ident => #slint_typ_name::#ident,
            }
        });
        quote! {
            impl Into<#slint_typ_name> for #kind_enum_name {
                fn into(self) -> #slint_typ_name {
                    match self {
                        #(#match_arms)*
                    }
                }
            }
        }
    };
    let kind_impl = {
        quote! {
            impl #item_name {
                pub fn kind(&self) -> #kind_enum_name {
                    self.into()
                }
            }
        }
    };
    let route_enum_impl = {
        quote! {
            impl stern::nav::RouteEnum for #item_name {
                type Kind = #kind_enum_name;
                type SlintKind = #slint_typ_name;
            }
        }
    };
    quote! {
        #item_with_attr

        #into_impl

        #kind_impl

        #route_enum_impl

        #re_exports
    }
    .into()
}

/// Attribute used on generated `InnerXxxAdopter` type.
///
/// This macro generates:
/// - `XxxScreenStates`, which contains [`PropertyHandle`]s for each properties
/// - `XxxViewModelTrait`, which contains each callback to be implemented
#[proc_macro_attribute]
pub fn adopter(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let item = parse_macro_input!(item as InnerGlobalComponent);
    adopter_inner(attr.into(), item).into()
}

#[proc_macro]
pub fn define_mapper_impl(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = parse_macro_input!(input as DefineMapperInput);
    mapper::generate(input).into()
}

fn state_struct_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}States", base)
}

fn viewmodel_trait_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}ViewModelTrait", &base)
}

fn public_global_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}Adopter", &base)
}

fn mapper_trait_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}PropertyMappers", &base)
}

fn mapper_trait_member_type_ident(prop_name: &Ident) -> Ident {
    format_ident!(
        "{}MappedType",
        prop_name.unraw().to_string().to_upper_camel_case()
    )
}

fn define_mapper_macro_ident(base_name: impl IdentFragment) -> Ident {
    let base_name = format_ident!("{}", base_name).to_string().to_snake_case();
    format_ident!("define_{}_mapper", &base_name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mapper_trait_member_type_ident_is_correct() {
        let prop_name = format_ident!("score");
        let member_type = mapper_trait_member_type_ident(&prop_name);
        assert_eq!(member_type, "ScoreMappedType");
    }

    #[test]
    fn define_mapper_macro_ident_is_correct() {
        let base_name = format_ident!("Start");
        let macro_name = define_mapper_macro_ident(&base_name);
        assert_eq!(macro_name, "define_start_mapper");
    }
}
