name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install fontconfig for slint
      run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev
    - name: Run checks
      run: cargo check --verbose --all-targets
    - name: Run tests
      run: cargo test --verbose
